version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      = "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  socio:
    build: .
    environment:
      DATABASE_DSN: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - postgres
      - redis
    ports:
      - "3015:3015"

volumes:
  db_data:
